version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grocery-booking-api
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: grocery-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - grocery-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  grocery-db-data:
    driver: local
